feat/pills
open-source-uc/UbiCate-v2 pull request #74
Opened 2024-08-13 12:45 UTC by MrBased

# Problema

Filtros de puntos de interés.

## Solución

- Pills para filtrar: almuerzo, baños, bibliotecas.
- Filtros por nombre y categoría. Ajustado para considerar la poca estandarización que tiene esta última propiedad.
- Layers con filtros de expresión de  Mapbox.

## Resuelve

Esta pull request resuelve la issue #60

2024-08-13 16:38 UTC, mc-cari requested changes
Buena se ven bien los pills.
Pero encontre un bug de que al comenzar a escribir en el cuadro de búsqueda del mapa ya no se muestran los resultados en el mapa.

2024-08-13 16:38 UTC, mc-cari commented on app/map/map.tsx
> +        <PillFilter geocoder={geocoder.current} setFilteredPlaces={setGeocoderPlaces} />
Aprovecharía de cambiar el nombre de `setGeocoderPlaces` por `setFilteredPlaces` igual.

2024-08-13 16:38 UTC, mc-cari commented on app/components/pillFilter.tsx
> +      />
Puedes agregar el Pill de salas porfa?

2024-08-14 03:46 UTC, MrBased commented
> bug de que al comenzar a escribir en el cuadro de búsqueda del mapa ya no se muestran los resultados en el mapa.

Es por el orden de los eventos, ya lo arreglo

2024-08-27 22:12 UTC, mc-cari approved these changes
Súper

2024-08-27 22:27 UTC, merged